### ISSUE TITLE
Add user input for the variables

### ISSUE THREAD

**Issue by Fox-Winther** [StephenTheMoldovan/NebulaSubtitleDownloader#1]
I saw in some parts of the code that you need to edit it a little for certain parts to work. Cant you add those as variables with user input values? Ie:

```
set /p "var="
echo %var%
```

That way it can be set without touching the code

**Comment by StephenTheMoldovan** [comment]
I always edited the batch file itself to include the link from where the subtitle fragments were pulled from (it varies from one video to another).
while I was at it, I would also set the number of the final fragment so that it would start with sub_en_0.vtt and go all the way to sub_en_n.vtt
you are free to fork the repo and do any edits you find to be necessary, but this batch file is what I used and I do not plan to do any further changes to it.
